data:
  raw_data_path: "source dataset/APA-DDoS-Dataset.csv"
  data_dir: "data/"
  train_path: "train.csv" 
  test_path: "test.csv"

train:
  test_size: 0.1
  random_state: 42
  shuffle: true

model:
  - name: DecisionTreeClassifier
    params:
      criterion: 'entropy'
      max_depth: 20
      min_samples_split: 10
      # min_samples_leaf: 1
      random_state: 42
    store_path: "models/"

  - name: RandomForestClassifier
    params:
      n_estimators: 100
      max_depth: 100
      min_samples_split: 10
      max_features: "sqrt"  
      random_state: 42
      # criterion: "log_loss"
      bootstrap: True
    store_path: "models/"

  - name: SVC
    params:
      C: 10.0
    store_path: "models/"

  - name: MLPClassifier
    params:
      hidden_layer_sizes: [50, 50]
      max_iter: 200
      random_state: 42
      alpha: 0.0001
      solver: "adam"
    store_path: "models/"

  - name: SGDClassifier
    params:
      loss: "hinge"
      penalty: "l2"
      learning_rate: "adaptive"
      max_iter: 1000
      eta0: 0.3
    store_path: "models/"

  - name: GaussianNB
    params:
      var_smoothing: 0.000000001
    store_path: "models/"

mlflow:
  tracking_uri: "./mlruns"
  experiment_name: "insurance_cross_sell"